# Generated by Django 4.0.6 on 2022-08-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
